spring:
  application:
    name: eureka-sv
  cloud:
    discovery:
      client:
        register-with-eureka: false
        fetch-registry: false
    inetutils:
      preferred-networks:
        - 127.0.0.1

server:
  port: 8761

eureka:
  instance:
    lease-renewal-interval-in-seconds: 0

