server:
  port: 8080

spring:
  application:
    name: productos-sv
  datasource:
    url: jdbc:mysql://localhost:3306/productos_bd?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url-defaultZone: http://localhost:8761/eureka
