server:
  port: 8090

spring:
  application:
    name: ventas-sv
  datasource:
    url: jdbc:mysql://localhost:3306/ventas_bd?serverTimezone=UTC
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  client:
    service-url-defaultZone: http://localhost:8761/eureka